-- =====================================================================
-- NutriOn — Cotas de IA + early adopters
-- Numera os usuários por ordem de cadastro (user_number) e marca os
-- 100 primeiros como early adopters (goodwill pra futuro modelo
-- premium). Cria ai_usage_log pra rastrear consumo de Sanity Check e
-- Onboarding Plan (chat continua contando via chat_messages).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Numeração + flag de early adopter
-- ---------------------------------------------------------------------
alter table public.profiles
  add column if not exists user_number integer
    generated by default as identity;

-- Flag computada: os 100 primeiros usuários por número.
-- Mantida como coluna stored (não precisa recalcular a cada select).
alter table public.profiles
  drop column if exists is_early_adopter;
alter table public.profiles
  add column is_early_adopter boolean
    generated always as (user_number <= 100) stored;

comment on column public.profiles.user_number is
  'Número sequencial de cadastro (1 = primeiro user). Imutável.';
comment on column public.profiles.is_early_adopter is
  'true para os 100 primeiros usuários (goodwill: ficam grátis quando IA virar premium).';

-- ---------------------------------------------------------------------
-- 2. Log de uso de IA (Sanity Check + Onboarding Plan)
-- ---------------------------------------------------------------------
create table if not exists public.ai_usage_log (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  feature text not null check (feature in ('sanity_check','onboarding_plan')),
  day date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_log_user_day_feature_idx
  on public.ai_usage_log (user_id, day, feature);

comment on table public.ai_usage_log is
  'Tracking de consumo de IA pra cotas diárias. Chat usa chat_messages.';

-- ---------------------------------------------------------------------
-- 3. RLS — owner-only (só leitura; insert é feito pelas edge functions)
-- ---------------------------------------------------------------------
alter table public.ai_usage_log enable row level security;

drop policy if exists "ai_usage_log_select_own" on public.ai_usage_log;
create policy "ai_usage_log_select_own" on public.ai_usage_log
  for select using (auth.uid() = user_id);

drop policy if exists "ai_usage_log_insert_own" on public.ai_usage_log;
create policy "ai_usage_log_insert_own" on public.ai_usage_log
  for insert with check (auth.uid() = user_id);
